// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.12
// source: task-workflow.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskWorkflowEventType int32

const (
	TaskWorkflowEventType_TASK_ADDED_EVENT    TaskWorkflowEventType = 0
	TaskWorkflowEventType_TASK_CLOSED_EVENT   TaskWorkflowEventType = 1
	TaskWorkflowEventType_TASK_SHUFFLED_EVENT TaskWorkflowEventType = 2
)

// Enum value maps for TaskWorkflowEventType.
var (
	TaskWorkflowEventType_name = map[int32]string{
		0: "TASK_ADDED_EVENT",
		1: "TASK_CLOSED_EVENT",
		2: "TASK_SHUFFLED_EVENT",
	}
	TaskWorkflowEventType_value = map[string]int32{
		"TASK_ADDED_EVENT":    0,
		"TASK_CLOSED_EVENT":   1,
		"TASK_SHUFFLED_EVENT": 2,
	}
)

func (x TaskWorkflowEventType) Enum() *TaskWorkflowEventType {
	p := new(TaskWorkflowEventType)
	*p = x
	return p
}

func (x TaskWorkflowEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskWorkflowEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_workflow_proto_enumTypes[0].Descriptor()
}

func (TaskWorkflowEventType) Type() protoreflect.EnumType {
	return &file_tasks_workflow_proto_enumTypes[0]
}

func (x TaskWorkflowEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskWorkflowEventType.Descriptor instead.
func (TaskWorkflowEventType) EnumDescriptor() ([]byte, []int) {
	return file_tasks_workflow_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_NEW_TASK_STATUS  TaskStatus = 0
	TaskStatus_DONE_TASK_STATUS TaskStatus = 1
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "NEW_TASK_STATUS",
		1: "DONE_TASK_STATUS",
	}
	TaskStatus_value = map[string]int32{
		"NEW_TASK_STATUS":  0,
		"DONE_TASK_STATUS": 1,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_workflow_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_tasks_workflow_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_tasks_workflow_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicID        string     `protobuf:"bytes,1,opt,name=PublicID,proto3" json:"PublicID,omitempty"`
	AccountPublicID string     `protobuf:"bytes,2,opt,name=AccountPublicID,proto3" json:"AccountPublicID,omitempty"`
	Description     string     `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Status          TaskStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=task.TaskStatus" json:"Status,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetPublicID() string {
	if x != nil {
		return x.PublicID
	}
	return ""
}

func (x *Task) GetAccountPublicID() string {
	if x != nil {
		return x.AccountPublicID
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_NEW_TASK_STATUS
}

type TaskWorkflowEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventID      string                `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	EventVersion string                `protobuf:"bytes,2,opt,name=EventVersion,proto3" json:"EventVersion,omitempty"`
	EventTime    string                `protobuf:"bytes,3,opt,name=EventTime,proto3" json:"EventTime,omitempty"`
	Producer     string                `protobuf:"bytes,4,opt,name=Producer,proto3" json:"Producer,omitempty"`
	EventName    TaskWorkflowEventType `protobuf:"varint,5,opt,name=EventName,proto3,enum=task.TaskWorkflowEventType" json:"EventName,omitempty"`
	TaskPayload  *Task                 `protobuf:"bytes,6,opt,name=TaskPayload,proto3" json:"TaskPayload,omitempty"`
}

func (x *TaskWorkflowEvent) Reset() {
	*x = TaskWorkflowEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasks_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskWorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskWorkflowEvent) ProtoMessage() {}

func (x *TaskWorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskWorkflowEvent.ProtoReflect.Descriptor instead.
func (*TaskWorkflowEvent) Descriptor() ([]byte, []int) {
	return file_tasks_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *TaskWorkflowEvent) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *TaskWorkflowEvent) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *TaskWorkflowEvent) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *TaskWorkflowEvent) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *TaskWorkflowEvent) GetEventName() TaskWorkflowEventType {
	if x != nil {
		return x.EventName
	}
	return TaskWorkflowEventType_TASK_ADDED_EVENT
}

func (x *TaskWorkflowEvent) GetTaskPayload() *Task {
	if x != nil {
		return x.TaskPayload
	}
	return nil
}

var File_tasks_workflow_proto protoreflect.FileDescriptor

var file_tasks_workflow_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2d, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x98, 0x01, 0x0a,
	0x04, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x44, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xf4, 0x01, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b,
	0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x5d,
	0x0a, 0x15, 0x54, 0x61, 0x73, 0x6b, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x41, 0x53, 0x4b, 0x5f,
	0x41, 0x44, 0x44, 0x45, 0x44, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x5f, 0x45, 0x56, 0x45,
	0x4e, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x48, 0x55,
	0x46, 0x46, 0x4c, 0x45, 0x44, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x2a, 0x37, 0x0a,
	0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x13, 0x0a, 0x0f, 0x4e,
	0x45, 0x57, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x44, 0x4f, 0x4e, 0x45, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x10, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x73,
	0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tasks_workflow_proto_rawDescOnce sync.Once
	file_tasks_workflow_proto_rawDescData = file_tasks_workflow_proto_rawDesc
)

func file_tasks_workflow_proto_rawDescGZIP() []byte {
	file_tasks_workflow_proto_rawDescOnce.Do(func() {
		file_tasks_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_tasks_workflow_proto_rawDescData)
	})
	return file_tasks_workflow_proto_rawDescData
}

var file_tasks_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tasks_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tasks_workflow_proto_goTypes = []interface{}{
	(TaskWorkflowEventType)(0), // 0: task.TaskWorkflowEventType
	(TaskStatus)(0),            // 1: task.TaskStatus
	(*Task)(nil),               // 2: task.Task
	(*TaskWorkflowEvent)(nil),  // 3: task.TaskWorkflowEvent
}
var file_tasks_workflow_proto_depIdxs = []int32{
	1, // 0: task.Task.Status:type_name -> task.TaskStatus
	0, // 1: task.TaskWorkflowEvent.EventName:type_name -> task.TaskWorkflowEventType
	2, // 2: task.TaskWorkflowEvent.TaskPayload:type_name -> task.Task
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tasks_workflow_proto_init() }
func file_tasks_workflow_proto_init() {
	if File_tasks_workflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tasks_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasks_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskWorkflowEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tasks_workflow_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tasks_workflow_proto_goTypes,
		DependencyIndexes: file_tasks_workflow_proto_depIdxs,
		EnumInfos:         file_tasks_workflow_proto_enumTypes,
		MessageInfos:      file_tasks_workflow_proto_msgTypes,
	}.Build()
	File_tasks_workflow_proto = out.File
	file_tasks_workflow_proto_rawDesc = nil
	file_tasks_workflow_proto_goTypes = nil
	file_tasks_workflow_proto_depIdxs = nil
}
